# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
