# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0002_auto_20170624_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thought',
            old_name='conditon',
            new_name='condition',
        ),
    ]
